<?xml version="1.0" encoding="utf-8"?><Database Name="jiu" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=jiu;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="jiuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admin">
    <Type Name="admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="用户名" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="密码" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="邮箱" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="手机号" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="收货地址" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.news" Member="news">
    <Type Name="news">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="添加内容" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="更新时间" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.zhaoshang" Member="zhaoshang">
    <Type Name="zhaoshang">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="用户名" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="留言内容" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="product">
    <Type Name="product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="产品名称" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="产品图片" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="产品类别" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="产品介绍" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WebConfig" Member="WebConfig">
    <Type Name="WebConfig">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="网站名称" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="网站地址" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>